name: Build Packages and Update Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    name: Build and Deploy on ${{ matrix.title }}
    strategy:
      matrix:
        include:
          - title: macOS
            os: macos-11
            platform: darwin
          - title: Windows
            os: windows-2022
            platform: win32
          - title: Linux (amd64)
            os: ubuntu-22.04
            arch: x64
            platform: linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 18

        # macOS: appears to fix https://github.com/electron/forge/issues/2807
      - name: Setup Python 3.11 (macOS)
        uses: actions/setup-python@v4
        if: matrix.platform == 'darwin'
        with:
          python-version: "3.11"

      - name: Cache npm Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/AppData/Local/npm-cache # Windows cache path
          key: ${{ matrix.os }}-npm-cache-${{ hashFiles('**/Sveltekit-App/package-lock.json', '**/Electron-App/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-npm-cache-

      - name: Install SvelteKit Dependencies
        run: |
          cd ./Sveltekit-App
          npm install

      - name: Install Electron Dependencies
        run: |
          cd ./Electron-App
          npm install

      - name: Build SvelteKit Application
        run: |
          cd ./Sveltekit-App
          npm run build

      - name: Build and Publish Electron Application
        run: |
          cd ./Electron-App
          npm run publish --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
